channels:
- conda-forge
dependencies:
- python=3.8.15
- pip<=22.3.1
- pip:
  - mlflow<3,>=2.1
  - astunparse==1.6.3
  - cloudpickle==2.2.0
  - ipython==8.7.0
  - torch-cluster==1.6.0
  - torch-geometric==2.2.0
  - torch-scatter==2.1.0
  - torch-sparse==0.6.16
  - torch-spline-conv==1.2.1
  - torch==1.12.0
name: mlflow-env
